if(NOT DEFINED RESULT_FILE OR NOT EXISTS "${RESULT_FILE}")
    message(FATAL_ERROR "Fuzz result file is missing: ${RESULT_FILE}")
endif()

file(STRINGS "${RESULT_FILE}" fuzz_results)
set(failures)
foreach(result IN LISTS fuzz_results)
    if(NOT result MATCHES "=0$")
        list(APPEND failures "${result}")
    endif()
endforeach()
if(failures)
    list(JOIN failures ", " failure_text)
    message(FATAL_ERROR "One or more fuzz targets failed: ${failure_text}")
endif()
